<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>xmouse</AssemblyName>
    <RootNamespace>XMouse</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>xmouse</Authors>
    <Product>xmouse</Product>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="tray.ico" CopyToOutputDirectory="PreserveNewest" Condition="Exists('tray.ico')" />
  </ItemGroup>

</Project>
